// Generates tree-shakeable named exports in src/lib/icons/generated.ts via @iconify-json/*.
/// <reference types="node" />
import { getIconData, iconToSVG } from '@iconify/utils'
import type { IconifyJSON } from '@iconify/types'
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { pathToFileURL } from 'node:url'
import * as custom from '../src/lib/icons/custom.ts'
import { iconify_icons } from './icons-manifest.ts'

const require_from_here = createRequire(import.meta.url)
const collections = new Map<string, IconifyJSON>()

const load_collection = async (prefix: string): Promise<IconifyJSON> => {
  const cached = collections.get(prefix)
  if (cached) return cached
  let path: string
  try {
    path = require_from_here.resolve(`@iconify-json/${prefix}/icons.json`)
  } catch {
    throw new Error(
      `Icon set '${prefix}' is not installed. Run: pnpm add -D @iconify-json/${prefix}`,
    )
  }
  const collection = JSON.parse(await readFile(path, `utf8`)) as IconifyJSON
  collections.set(prefix, collection)
  return collection
}

const single_path = /^<path(?<attrs>(?:\s+[a-z-]+="[^"]*")*)\s*\/>$/
const path_d = /\s+d="(?<value>[^"]+)"/
const current_color_fill = /\s+fill="currentColor"/
export const escape_template_literal = (value: string): string =>
  value.replaceAll(`\\`, `\\\\`).replaceAll(`\``, `\\\``).replaceAll(`\${`, `\\\${`)
const as_markup = (body: string) => `markup: \`${escape_template_literal(body)}\``

const as_shape = (body: string): string => {
  const attrs = single_path.exec(body)?.groups?.attrs
  const d = attrs && path_d.exec(attrs)?.groups?.value
  const extra_attrs = attrs?.replace(path_d, ``).replace(current_color_fill, ``)
  if (!d || extra_attrs) return as_markup(body)
  return `d: \`${escape_template_literal(d)}\``
}

export const generate_icons = async (): Promise<void> => {
  // Compared case-insensitively: `Npm` alongside custom.ts `NPM` compiles and passes every
  // exact-match check, then ships the same glyph twice under two spellings.
  const reserved = new Map(Object.keys(custom).map((name) => [name.toLowerCase(), name]))
  const claimed_ids = new Map<string, string>()
  const entries: string[] = []
  const problems: string[] = []

  for (const [name, icon_id] of Object.entries(iconify_icons)) {
    const clash = reserved.get(name.toLowerCase())
    if (clash) {
      problems.push(`${name}: already exported from custom.ts as '${clash}'`)
      continue
    }
    const duplicate_of = claimed_ids.get(icon_id)
    if (duplicate_of) {
      problems.push(`${name}: '${icon_id}' already exported as '${duplicate_of}'`)
      continue
    }
    claimed_ids.set(icon_id, name)
    const [prefix, id] = icon_id.split(`:`)
    const collection = await load_collection(prefix)
    const data = getIconData(collection, id)
    if (!data) {
      problems.push(`${name}: '${icon_id}' not in @iconify-json/${prefix}`)
      continue
    }
    const { body, attributes } = iconToSVG(data, { height: `none` })
    // one line per glyph (same shape as custom.ts); trailing comment keeps the Iconify id greppable
    entries.push(
      `export const ${name} = { viewBox: \`${escape_template_literal(attributes.viewBox)}\`, ${as_shape(body.trim())} } satisfies IconData // ${icon_id}`,
    )
  }

  if (problems.length > 0) {
    throw new Error(`Bad manifest entries:\n  ${problems.join(`\n  `)}`)
  }

  const file = [
    `// GENERATED by scripts/generate-icons.ts — edit icons-manifest.ts and run \`pnpm gen:icons\`.`,
    `import type { IconData } from './types'`,
    ``,
    ...entries,
    ``,
  ].join(`\n`)

  const output_url = new URL(`../src/lib/icons/generated.ts`, import.meta.url)
  const current_file = await readFile(output_url, `utf8`).catch((error: unknown) => {
    if (error instanceof Error && `code` in error && error.code === `ENOENT`) return
    throw error
  })
  if (current_file === file) return
  await writeFile(output_url, file)
  console.info(
    `generated ${Object.keys(iconify_icons).length} icons from ${collections.size} sets`,
  )
}

const entry_path = process.argv[1]
if (entry_path && import.meta.url === pathToFileURL(entry_path).href)
  await generate_icons()
